version: '2'

services:
  ce:
    container_name: 'gitlab-ce'
    image: 'gitlab/gitlab-ce:latest'
    restart: 'always'
    hostname: 'git.bmi.ac.cn'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://10.9.9.112:10080'
        gitlab_rails['gitlab_shell_ssh_port'] = 10022
    ports:
      - '10.9.9.112:10080:10080'
      - '10.9.9.112:10022:22'
    volumes:
      - '../../volumes/gitlab/config:/etc/gitlab'
      - '../../volumes/gitlab/logs:/var/log/gitlab'
      - '../../volumes/gitlab/data:/var/opt/gitlab'

  runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: 'gitlab-runner'
    volumes:
      - '../../volumes/gitlab/runner:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always

