gitlab:
  container_name: 'gitlab'
  image: 'gitlab/gitlab-ce:latest'
  restart: 'always'
  hostname: 'git.bmi.ac.cn'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://10.9.9.112:10080'
      gitlab_rails['gitlab_shell_ssh_port'] = 10022
  ports:
    - '10.9.9.112:10080:10080'
    - '10.9.9.112:10022:22'
  volumes:
    - '../../volumes/gitlab/config:/etc/gitlab'
    - '../../volumes/gitlab/logs:/var/log/gitlab'
    - '../../volumes/gitlab/data:/var/opt/gitlab'

# sudo docker run --detach \
# --publish 10080:10080 --publish 10022:22 \
# --name gitlab \
# --restart always \
# --volume ../../volumes/gitlab/config:/etc/gitlab \
# --volume ../../volumes/gitlab/logs:/var/log/gitlab \
# --volume ../../volumes/gitlab/data:/var/opt/gitlab \
# gitlab/gitlab-ce:latest
